// FETCH TODOS
export const FETCH_TODOS_REQUEST="FETCH_TODOS_REQUEST";
export const FETCH_TODOS_SUCCESS="FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_FAILURE="FETCH_TODOS_FAILURE";



// CREATE TODO
export const CREATE_TODO_REQUEST="CREATE_TODO_REQUEST";
export const CREATE_TODO_SUCCESS="CREATE_TODO_SUCCESS";
export const CREATE_TODO_FAILURE="CREATE_TODO_FAILURE";




// UPDATE TODO TITLE
export const UPDATE_TODO_TITLE_REQUEST="UPDATE_TODO_TITLE_REQUEST";
export const UPDATE_TODO_TITLE_SUCCESS="UPDATE_TODO_TITLE_SUCCESS";
export const UPDATE_TODO_TITLE_FAILURE="UPDATE_TODO_TITLE_FAILURE";




// UPDATE TODO STATUS
export const UPDATE_TODO_STATUS_REQUEST="UPDATE_TODO_STATUS_REQUEST";
export const UPDATE_TODO_STATUS_SUCCESS="UPDATE_TODO_STATUS_SUCCESS";
export const UPDATE_TODO_STATUS_FAILURE="UPDATE_TODO_STATUS_FAILURE";




// DELETE TODO
export const DELETE_TODO_REQUEST="DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS="DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAILURE="DELETE_TODO_FAILURE";